### ISSUE TITLE
Update 1.15.2 Seems doesn't work.

### ISSUE THREAD

**Issue by Trackhe** [DerFrZocker/Fast-WorldBorder-Fill#1]
when i Update the pom and the imports is coused in cannot find symbol  playChunkMap.cache

**Comment by Trackhe** [comment]
https://www.spigotmc.org/threads/playerchunkmap-cache-cannot-find-symbol-update-plugin-from-1-14-4.422699/

**Comment by DerFrZocker** [comment]
The synchronization of playerChunkMap.cache unnecessary, and you can remove it from the code. Beside that there is a to 1.15 updated development branch.

**Comment by Trackhe** [comment]
merci

**Comment by Trackhe** [comment]
With the Development Branche i have these error.
`Exception in thread "Thread-43" java.lang.NoClassDefFoundError: de/derfrzocker/spigot/utils/ChunkCoordIntPair
[18:44:18 WARN]:        at de.derfrzocker.fast.worldborder.fill.FastWorldBorderFill.lambda$onCommand$0(FastWorldBorderFill.java:131)
[18:44:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:830)
[18:44:18 WARN]: Caused by: java.lang.ClassNotFoundException: de.derfrzocker.spigot.utils.ChunkCoordIntPair
[18:44:18 WARN]:        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
[18:44:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
[18:44:18 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[18:44:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[18:44:18 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[18:44:18 WARN]:        ... 2 more`

**Comment by Trackhe** [comment]
I dont know i can run it only when i use /fast-fill 32 100 1000 1000 10 0 0 world
/fast-fill 32 100 100 100 10 0 0 world for testing is not possible.
Und eigendlich können wir deutsch schreiben ^^ hi.
Der server meldet die ganze zeit nur nach dem das plugin sagt es startet das der mainthread blockiert ist. ich nutze paper. liegt das vllt daran?
Die map größe verändert sich nicht.

**Comment by Trackhe** [comment]
```
[19:10:10 ERROR]: ------------------------------
[19:10:10 ERROR]: Current Thread: Thread-65
[19:10:10 ERROR]:       PID: 131 | Suspended: false | Native: false | State: BLOCKED
[19:10:10 ERROR]:       Thread is waiting on monitor(s):
[19:10:10 ERROR]:               Locked on:app//com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[19:10:10 ERROR]:               Locked on:de.derfrzocker.fast.worldborder.fill.api.WorldBorderThread.run(WorldBorderThread.java:62)
[19:10:10 ERROR]:       Stack:
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1$1.load(WorldBorderFillTask_v1_15_R1.java:75)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1$1.load(WorldBorderFillTask_v1_15_R1.java:71)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache.get(LocalCache.java:4154)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1.getIChunkAccess(WorldBorderFillTask_v1_15_R1.java:427)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1.lambda$generate$3(WorldBorderFillTask_v1_15_R1.java:268)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1$$Lambda$4328/0x0000000801aed840.run(Unknown Source)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.api.WorldBorderThread.run(WorldBorderThread.java:62)
[19:10:10 ERROR]: ------------------------------
[19:10:10 ERROR]: Current Thread: Thread-66
[19:10:10 ERROR]:       PID: 132 | Suspended: false | Native: false | State: BLOCKED
[19:10:10 ERROR]:       Thread is waiting on monitor(s):
[19:10:10 ERROR]:               Locked on:app//com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[19:10:10 ERROR]:               Locked on:de.derfrzocker.fast.worldborder.fill.api.WorldBorderThread.run(WorldBorderThread.java:62)
[19:10:10 ERROR]:       Stack:
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1$1.load(WorldBorderFillTask_v1_15_R1.java:75)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1$1.load(WorldBorderFillTask_v1_15_R1.java:71)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache.get(LocalCache.java:4154)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
[19:10:10 ERROR]:               app//com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1.getIChunkAccess(WorldBorderFillTask_v1_15_R1.java:427)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1.lambda$generate$3(WorldBorderFillTask_v1_15_R1.java:268)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1$$Lambda$4328/0x0000000801aed840.run(Unknown Source)
[19:10:10 ERROR]:               de.derfrzocker.fast.worldborder.fill.api.WorldBorderThread.run(WorldBorderThread.java:62)
[19:10:10 ERROR]: ------------------------------
[19:10:10 ERROR]: Current Thread: Netty Server IO #2
[19:10:10 ERROR]:       PID: 134 | Suspended: false | Native: false | State: RUNNABLE
[19:10:10 ERROR]:       Thread is waiting on monitor(s):
[19:10:10 ERROR]:               Locked on:java.base@13.0.2/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
[19:10:10 ERROR]:               Locked on:java.base@13.0.2/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
[19:10:10 ERROR]:       Stack:
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:339)
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:167)
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
[19:10:10 ERROR]:               app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
[19:10:10 ERROR]:               app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
[19:10:10 ERROR]:               app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:10:10 ERROR]:               java.base@13.0.2/java.lang.Thread.run(Thread.java:830)
[19:10:10 ERROR]: ------------------------------
[19:10:10 ERROR]: Current Thread: Netty Server IO #3
[19:10:10 ERROR]:       PID: 135 | Suspended: false | Native: false | State: RUNNABLE
[19:10:10 ERROR]:       Thread is waiting on monitor(s):
[19:10:10 ERROR]:               Locked on:java.base@13.0.2/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
[19:10:10 ERROR]:               Locked on:java.base@13.0.2/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
[19:10:10 ERROR]:       Stack:
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:339)
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:167)
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
[19:10:10 ERROR]:               java.base@13.0.2/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
[19:10:10 ERROR]:               app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
[19:10:10 ERROR]:               app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
[19:10:10 ERROR]:               app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:10:10 ERROR]:               java.base@13.0.2/java.lang.Thread.run(Thread.java:830)
[19:10:10 ERROR]: ------------------------------
```

**Comment by DerFrZocker** [comment]
Benutze am besten Spigot, Paper funktioniert nicht, da es den weg wie chunks generiert / geladen / gespeichert werden verändert. Und es deswegen, dafür eine andere Herangehensweise braucht (Es sollte auch keine Performance Veränderung geben wen du Spigot statt Paper benutzt bei der Generierung). 
Das du keinen kleineren Bereich generieren kannst, liegt an diesen zwei Abfragen [https://github.com/DerFrZocker/Fast-WorldBorder-Fill/blob/development/src/main/java/de/derfrzocker/fast/worldborder/fill/impl/BasicRegion.java#L26](url)

Diese kannst du entfernen. Die Abfragen sind noch ein Überbleibsel, des ersten Entwurfes wie ich es handhaben wollte, aber mich dann doch um entschieden habe.

**Comment by Trackhe** [comment]
Cool Danke ich teste es und schreib dann nochmal hier. :) Danke für deine Arbeit.

**Comment by Trackhe** [comment]
it works i reach up to 26% highpeak 55%. not bad. Schon wieder englisch is irgendwie drinn xD
