### ISSUE TITLE
Generiert nicht weiter.

### ISSUE THREAD

**Issue by Trackhe** [DerFrZocker/Fast-WorldBorder-Fill#2]
command: fast-fill 32 100 10000 10000 0 0 0 world
```
[10:53:37] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: Begin with BIOMES
[10:53:37] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: End BIOMES
[10:53:37] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: Begin with NOISE
[10:53:37] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: End NOISE
[10:53:37] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: Begin with SURFACE, CARVERS, LIQUID_CARVERS
[10:53:38] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: End SURFACE, CARVERS, LIQUID_CARVERS
[10:53:38] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: Begin with FEATURES
[10:53:38] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: End FEATURES
[10:53:38] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: Begin with SPAWN, HEIGHTMAPS
[10:53:38] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 26: End SPAWN, HEIGHTMAPS
[10:53:50] [Thread-27/INFO]: [Fast-WorldBorder-Fill] 27: Begin with STRUCTURE_STARTS
[10:53:53] [Thread-40/WARN]: java.util.ConcurrentModificationException

[10:53:53] [Thread-40/WARN]:    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)

[10:53:53] [Thread-40/WARN]:    at net.minecraft.server.v1_15_R1.WorldChunkManager.a(SourceFile:102)

[10:53:53] [Thread-40/WARN]:    at net.minecraft.server.v1_15_R1.ChunkGenerator.createStructures(ChunkGenerator.java:142)

[10:53:53] [Thread-40/WARN]:    at net.minecraft.server.v1_15_R1.ChunkStatus.d(SourceFile:51)

[10:53:53] [Thread-40/WARN]:    at net.minecraft.server.v1_15_R1.ChunkStatus.a(SourceFile:214)

[10:53:53] [Thread-40/WARN]:    at de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1.lambda$generate$3(WorldBorderFillTask_v1_15_R1.java:323)

[10:53:53] [Thread-40/WARN]:    at de.derfrzocker.fast.worldborder.fill.api.WorldBorderThread.run(WorldBorderThread.java:62)

[10:53:53] [Thread-61/WARN]: java.util.ConcurrentModificationException

[10:53:53] [Thread-61/WARN]:    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)

[10:53:53] [Thread-61/WARN]:    at net.minecraft.server.v1_15_R1.WorldChunkManager.a(SourceFile:102)

[10:53:53] [Thread-61/WARN]:    at net.minecraft.server.v1_15_R1.ChunkGenerator.createStructures(ChunkGenerator.java:142)

[10:53:53] [Thread-61/WARN]:    at net.minecraft.server.v1_15_R1.ChunkStatus.d(SourceFile:51)

[10:53:53] [Thread-61/WARN]:    at net.minecraft.server.v1_15_R1.ChunkStatus.a(SourceFile:214)

[10:53:53] [Thread-61/WARN]:    at de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1.lambda$generate$3(WorldBorderFillTask_v1_15_R1.java:323)

[10:53:53] [Thread-61/WARN]:    at de.derfrzocker.fast.worldborder.fill.api.WorldBorderThread.run(WorldBorderThread.java:62)

[10:53:53] [Thread-60/WARN]: java.util.ConcurrentModificationException

[10:53:53] [Thread-60/WARN]:    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)

[10:53:53] [Thread-60/WARN]:    at net.minecraft.server.v1_15_R1.WorldChunkManager.a(SourceFile:102)

[10:53:53] [Thread-60/WARN]:    at net.minecraft.server.v1_15_R1.ChunkGenerator.createStructures(ChunkGenerator.java:142)

[10:53:53] [Thread-60/WARN]:    at net.minecraft.server.v1_15_R1.ChunkStatus.d(SourceFile:51)

[10:53:53] [Thread-60/WARN]:    at net.minecraft.server.v1_15_R1.ChunkStatus.a(SourceFile:214)

[10:53:53] [Thread-60/WARN]:    at de.derfrzocker.fast.worldborder.fill.impl.WorldBorderFillTask_v1_15_R1.lambda$generate$3(WorldBorderFillTask_v1_15_R1.java:323)

[10:53:53] [Thread-60/WARN]:    at de.derfrzocker.fast.worldborder.fill.api.WorldBorderThread.run(WorldBorderThread.java:62)
```
Kommt immer wieder. Die Map wird dann auch nicht größer.

**Comment by DerFrZocker** [comment]
Das ist ein Problem, welches ich dachte, gelöst gehabt zu haben. Anscheinend nicht, werde es mir am Wochenende anschauen.

**Comment by Trackhe** [comment]
Have you had Time?

**Comment by Trackhe** [comment]
@DerFrZocker Bin tatsächlich immer noch Interessiert. Wie siehts aus? Wann hast du mal zeit :)? Oder hast du vielleicht ne Info woran es liegen könnte. Weil du ja meintest dass du dachtest es gelöst zu haben. Vielleicht kann ich dann ne Lösung finden und nen Pullreq erstellen.

**Comment by Trackhe** [comment]
@DerFrZocker hast du vllt nen ansatz? Für die neue Version so wie für die Problemlösung? Würde dann nen pullreq anfertigen

**Comment by DerFrZocker** [comment]
Die code basis ist ziemlich schlecht und sollte eigentlich komplett neu geschrieben werden. So ziemlich der ganze Ansatz zeigt wie schlecht ich die Welten Generation früher verstanden habe.
